"""Write docs/COST.md: token usage from the log x model prices, projected per month (FR-11)."""

from __future__ import annotations

from functools import lru_cache

import yaml
from sqlmodel import select

from app.settings import REPO_ROOT, settings
from app.store.db import get_session
from app.store.models import Event, Message


@lru_cache(maxsize=1)
def _prices() -> dict:
    cfg = yaml.safe_load((settings.config_dir / "pricing.yaml").read_text())
    return cfg["models"]


def _per_million(tokens: int, price_per_m: float) -> float:
    return tokens / 1_000_000 * price_per_m


def _measure() -> dict:
    """Average input/output tokens per message from this run's triage events."""
    with get_session() as session:
        msgs = session.exec(select(Message)).all()
        events = session.exec(select(Event).where(Event.action == "triage")).all()
        n = max(len(msgs), 1)
        in_tok = sum(e.input_tokens for e in events)
        out_tok = sum(e.output_tokens for e in events)
        model = events[0].model if events else "n/a"
    # Triage tokens are measured. A guest-facing draft carries policy + tool context, so we
    # estimate it at ~3x the triage input and ~10x the triage output (documented assumption).
    avg_in = max(in_tok / n, 120)
    avg_out = max(out_tok / n, 60)
    return {
        "n": n,
        "model": model,
        "triage_in": avg_in,
        "triage_out": avg_out,
        "draft_in": avg_in * 3,
        "draft_out": avg_out * 10,
    }


def _monthly(cost_per_msg: float, per_day: int) -> float:
    return cost_per_msg * per_day * 30


def build() -> str:
    p = _prices()
    m = _measure()
    haiku, sonnet = p["claude-haiku"], p["claude-sonnet"]

    # Scenario A: Haiku triage + Sonnet draft (a draft is written for ~half of messages).
    draft_share = 0.5
    triage_cost = _per_million(m["triage_in"], haiku["input"]) + _per_million(m["triage_out"], haiku["output"])
    draft_cost = _per_million(m["draft_in"], sonnet["input"]) + _per_million(m["draft_out"], sonnet["output"])
    a_per_msg = triage_cost + draft_share * draft_cost

    # Scenario B: Haiku for everything.
    draft_cost_h = _per_million(m["draft_in"], haiku["input"]) + _per_million(m["draft_out"], haiku["output"])
    b_per_msg = triage_cost + draft_share * draft_cost_h

    def row(label: str, per_msg: float) -> str:
        return (
            f"| {label} | ${per_msg:.5f} | ${_monthly(per_msg, 100):,.2f} | "
            f"${_monthly(per_msg, 500):,.2f} | ${_monthly(per_msg, 2000):,.2f} |"
        )

    return f"""# Cost estimate

Generated by `make demo` from this run's logged tokens (provider: `{m["model"]}`, {m["n"]} messages)
times the model prices in `config/pricing.yaml`. **Placeholder prices - confirm current Anthropic
pricing before quoting a client.**

Measured per message: triage ~{m["triage_in"]:.0f} in / {m["triage_out"]:.0f} out tokens. A
guest-facing draft is estimated at ~3x the triage input and ~10x the output (policy + tool context),
and drafts are written for roughly half of messages.

## Projected monthly cost

| Setup | Per message | 100 msg/day | 500 msg/day | 2,000 msg/day |
|---|---|---|---|---|
{row("Haiku triage + Sonnet drafts", a_per_msg)}
{row("Haiku only", b_per_msg)}

A local model (Ollama) is $0 in API cost; the trade-off is your own hardware and lower accuracy.

## Note on volume

A marina and campground is seasonal. Summer weekends and holiday weekends (Memorial Day, July 4th,
Labour Day) drive the message volume, so budget against peak weeks, not the yearly average. The
per-message cost is tiny; the bill is set by how many messages arrive, and a human still approves
every guest-facing reply.
"""


def main() -> None:
    path = REPO_ROOT / "docs" / "COST.md"
    path.parent.mkdir(parents=True, exist_ok=True)  # docs/ isn't in the deploy image
    path.write_text(build())
    print(f"Wrote {path.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
